package v1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// BehaviorStubSpec 定义行为注入规则
type BehaviorStubSpec struct {
	Mode         string          `json:"mode"` // local, remote
	LocalConfig  *LocalConfig    `json:"localConfig,omitempty"`
	ScriptVolume ScriptVolume    `json:"scriptVolume"`
	Behaviors    []Behavior      `json:"behaviors"`
	Advanced     *AdvancedConfig `json:"advanced,omitempty"`
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BehaviorStubSpec) DeepCopyInto(out *BehaviorStubSpec) {
	*out = *in
	if in.LocalConfig != nil {
		in, out := &in.LocalConfig, &out.LocalConfig
		*out = new(LocalConfig)
		(*in).DeepCopyInto(*out)
	}
	out.ScriptVolume = in.ScriptVolume
	if in.Behaviors != nil {
		in, out := &in.Behaviors, &out.Behaviors
		*out = make([]Behavior, len(*in))
		copy(*out, *in)
	}
	if in.Advanced != nil {
		in, out := &in.Advanced, &out.Advanced
		*out = new(AdvancedConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BehaviorStubSpec.
func (in *BehaviorStubSpec) DeepCopy() *BehaviorStubSpec {
	if in == nil {
		return nil
	}
	out := new(BehaviorStubSpec)
	in.DeepCopyInto(out)
	return out
}

// LocalConfig Local 模式配置
type LocalConfig struct {
	TargetSelector   metav1.LabelSelector         `json:"targetSelector"`
	SidecarImage     string                       `json:"sidecarImage"`
	SidecarResources *corev1.ResourceRequirements `json:"sidecarResources,omitempty"`
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalConfig) DeepCopyInto(out *LocalConfig) {
	*out = *in
	in.TargetSelector.DeepCopyInto(&out.TargetSelector)
	if in.SidecarResources != nil {
		in, out := &in.SidecarResources, &out.SidecarResources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalConfig.
func (in *LocalConfig) DeepCopy() *LocalConfig {
	if in == nil {
		return nil
	}
	out := new(LocalConfig)
	in.DeepCopyInto(out)
	return out
}

// ScriptVolume 脚本存储卷配置
type ScriptVolume struct {
	HostPath  string `json:"hostPath"`
	MountPath string `json:"mountPath"`
}

// Behavior 单个行为注入配置
type Behavior struct {
	Name          string `json:"name"`
	TargetPath    string `json:"targetPath"`              // 目标可执行文件路径
	ScriptPath    string `json:"scriptPath"`              // 用户脚本路径（相对于 scriptVolume.mountPath）
	EnableLogging bool   `json:"enableLogging,omitempty"` // 是否启用日志记录
	LogPath       string `json:"logPath,omitempty"`       // 日志文件路径
}

// AdvancedConfig 高级配置
type AdvancedConfig struct {
	EnableLogging       bool `json:"enableLogging,omitempty"`
	SyncIntervalSeconds int  `json:"syncIntervalSeconds,omitempty"`
}

// BehaviorStubStatus defines the observed state of BehaviorStub
type BehaviorStubStatus struct {
	// Phase 表示当前状态阶段：Pending, Running, Failed
	Phase string `json:"phase,omitempty"`
	// InjectedPods 已注入的 Pod 数量
	InjectedPods int32 `json:"injectedPods,omitempty"`
	// TotalPods 目标 Pod 总数
	TotalPods int32 `json:"totalPods,omitempty"`
	// LastUpdateTime 最后更新时间
	LastUpdateTime *metav1.Time `json:"lastUpdateTime,omitempty"`
	// Conditions 状态条件
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BehaviorStubStatus) DeepCopyInto(out *BehaviorStubStatus) {
	*out = *in
	if in.LastUpdateTime != nil {
		in, out := &in.LastUpdateTime, &out.LastUpdateTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BehaviorStubStatus.
func (in *BehaviorStubStatus) DeepCopy() *BehaviorStubStatus {
	if in == nil {
		return nil
	}
	out := new(BehaviorStubStatus)
	in.DeepCopyInto(out)
	return out
}

//+kubebuilder:object:root=true
//+kubebuilder:subresource:status
//+kubebuilder:resource:shortName=bs

// BehaviorStub is the Schema for the behaviorstubs API
type BehaviorStub struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   BehaviorStubSpec   `json:"spec,omitempty"`
	Status BehaviorStubStatus `json:"status,omitempty"`
}

//+kubebuilder:object:root=true

// BehaviorStubList contains a list of BehaviorStub
type BehaviorStubList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BehaviorStub `json:"items"`
}
